// <auto-generated />
namespace Webmap_1A.Migrations.Orders
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrderStatusatModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderStatusatModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201802261238394_Order Status at Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
